target-version="py311"

# Rule selection.
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP",  # pyupgrade
]

# Rule configuration.
line-length = 120

[extend-per-file-ignores]
"templates/shift-assignment-ortools/main.py" = ["C901"]
"templates/shift-planning-ortools/main.py" = ["C901"]
"templates/shift-assignment-pyomo/main.py" = ["C901"]
