name: go build & test
on: [push]
jobs:
  sdk-go-build-test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/nextmv-io/*
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      RESOURCES: resources
      NEXTMV_LIBRARY_PATH: ~/.nextmv/lib
    steps:
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: setup SSH Keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.NEXTMVBOT_SSH_KEY }}"

      - name: use ssh instead of https for git
        run: git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: initialize local branch name
        run: echo "LOCAL_BRANCH=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV

      # Gets the token and stores it in a variable.
      - name: export local branch
        run: echo "BRANCH_CHECK=$(git ls-remote --heads https://github.com/nextmv-io/plugins ${{ env.LOCAL_BRANCH }})" >> $GITHUB_ENV

      - name: override with develop if empty
        if: "${{ env.BRANCH_CHECK == '' }}"
        run: echo "LOCAL_BRANCH=develop" >> $GITHUB_ENV

      - name: git clone
        uses: actions/checkout@v3

      - name: clone plugins repository
        uses: actions/checkout@v3
        with:
          repository: nextmv-io/plugins
          path: ${{ env.RESOURCES }}
          ref: ${{ env.LOCAL_BRANCH }}
          ssh-key: ${{ secrets.NEXTMVBOT_SSH_KEY }}
          ssh-known-hosts: ssh-keyscan github.com

      # Installs Nextmv CLI dependency regardless of the distribution.
      - name: install Nextmv CLI dependency
        run: |
          NEXTMV_API_KEY=${{ secrets.API_KEY_PROD }} NEXTMV_BASE_URL=https://api.cloud.nextmv.io bash <(curl -s "https://cloud.nextmv.io/install-cli.txt")
          mv ~/.nextmv/nextmv /usr/local/bin/nextmv
          chmod a+x /usr/local/bin/nextmv

      - name: configure Nextmv CLI
        run: |
          echo ${{ secrets.NEXTMV_TOKEN }} >> ~/.nextmv/tokens/${{ secrets.API_KEY_PROD }}
          nextmv configure -a ${{ secrets.API_KEY_PROD }}

      - name: export sdk path used in this action
        run: echo "SDK_PATH=$(pwd)" >> $GITHUB_ENV

      - name: build plugins
        run: |

          # To get testing working, the dependency that plugins uses for sdk is
          # replaced for the local sdk repo checked out in this action.
          go mod edit -replace=github.com/nextmv-io/sdk=${{env.SDK_PATH}}

          # Build the plugins.
          REMOVE_TRIMPATH=1 NEXTMV_LIBRARY_PATH=${{ env.NEXTMV_LIBRARY_PATH }} bash scripts/build.sh > /dev/null 2>&1
        working-directory: ${{env.RESOURCES}}

      - name: go build
        run: go build -v ./...

      - name: go test
        run: NEXTMV_LIBRARY_PATH=${{ env.NEXTMV_LIBRARY_PATH }} go test ./...
