name: go-test
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  sdk-go-build-test:
    runs-on: ubuntu-latest
    # Use a matrix strategy to test all the modules simultaneously.
    strategy:
      fail-fast: false
      matrix:
        MOD_PATH:
          [
            ./,
            ./measure/google,
            ./measure/here,
            ./measure/osrm,
            ./measure/routingkit,
          ]
    steps:
      # Checks out the changes.
      - name: git clone
        uses: actions/checkout@v4

      # Sets up Go with the version set before.
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      # Builds the Go code.
      - name: go build
        run: go build -v ./...
        working-directory: sdk/${{ matrix.MOD_PATH }}

      # Runs the Go tests.
      - name: go test
        run: go test ./...
        working-directory: sdk/${{ matrix.MOD_PATH }}
