name: markdown lint
on: [push]
jobs:
  sdk-markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3

      - uses: DavidAnson/markdownlint-cli2-action@v7
        with:
          globs: "**/*.md"
